org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024M
android.useAndroidX=true
android.enableJetifier=true
kotlin.incremental=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024M
kotlin.incremental=true
